### ISSUE TITLE
Implement RUN and IBU

### ISSUE THREAD

**Issue by mirkobunse** [mirkobunse/CherenkovDeconvolution.py#1]
Before implementing the actual algorithms, I have to implement the following features:

- a test case for `util.fit_R`
- clustering of observables
- a convenience function obtaining `R` and `g` from `X_data`, `X_train`, and `y_train`

**Comment by maxnoe** [comment]
Module has code for `run` and `ibu`. What is missing?

**Comment by mirkobunse** [comment]
You're totally right, I forgot to close this issue when committing the implementation.
